#!/bin/bash
# ─────────────────────────────────────────────────────────────────────────────
# AI Predictor & Auto-Healer — Production Deploy (real healing, local image, zero external)
# ─────────────────────────────────────────────────────────────────────────────
set -euo pipefail

IMAGE_NAME="${IMAGE_NAME:-ai-predictor-healer}"
IMAGE_TAG="${IMAGE_TAG:-production}"
NAMESPACE="ai-healer-system"
FULL_IMAGE="${IMAGE_NAME}:${IMAGE_TAG}"

echo "⚠️  ─────────────────────────────────────────────────────────────────────"
echo "⚠️  PRODUCTION MODE: Real healing actions WILL be performed on the cluster"
echo "⚠️  ─────────────────────────────────────────────────────────────────────"
echo ""
read -rp "Type 'yes' to continue: " confirm
if [[ "${confirm}" != "yes" ]]; then
  echo "Aborted."
  exit 1
fi

# ── Guard: vendor/ must exist ─────────────────────────────────────────────────
if [ ! -d "vendor" ]; then
  echo ""
  echo "❌ vendor/ directory not found. Run: make vendor"
  echo ""
  exit 1
fi

# ── Guard: cluster must be reachable ──────────────────────────────────────────
echo "🔍 Checking Kubernetes cluster connectivity..."
if ! kubectl cluster-info --request-timeout=10s >/dev/null 2>&1; then
  echo ""
  echo "❌ Cannot reach a Kubernetes cluster."
  echo "   Start your cluster then retry. Verify with: kubectl cluster-info"
  echo ""
  exit 1
fi

CTX=$(kubectl config current-context 2>/dev/null || echo "none")
echo "✅ Cluster reachable: ${CTX}"

# ── Step 1: Build ─────────────────────────────────────────────────────────────
echo ""
echo "🔨 Building production image ${FULL_IMAGE} (offline, using vendor/)..."
docker build -t "${FULL_IMAGE}" .
echo "✅ Image built"

# ── Step 2: Load into cluster ─────────────────────────────────────────────────
echo ""
if echo "${CTX}" | grep -q "minikube"; then
  echo "📤 Loading into minikube..."
  minikube image load "${FULL_IMAGE}"
  echo "✅ Loaded"
elif echo "${CTX}" | grep -q "kind"; then
  CLUSTER_NAME=$(echo "${CTX}" | sed 's/kind-//')
  echo "📤 Loading into kind cluster '${CLUSTER_NAME}'..."
  kind load docker-image "${FULL_IMAGE}" --name "${CLUSTER_NAME}"
  echo "✅ Loaded"
else
  echo "ℹ️  Generic cluster — push to your registry if needed."
fi

# ── Step 3: Write production manifest ─────────────────────────────────────────
PROD_MANIFEST="deployments/deployment-production.yaml"
cat > "${PROD_MANIFEST}" << YAML
# Auto-generated by deploy-production.sh — do not edit manually
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-predictor-healer-production
  namespace: ${NAMESPACE}
  labels:
    app: ai-predictor-healer-production
    app.kubernetes.io/name: k8s-ai-healer
    app.kubernetes.io/version: "4.0"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ai-predictor-healer-production
  template:
    metadata:
      labels:
        app: ai-predictor-healer-production
    spec:
      serviceAccountName: ai-predictor-healer
      containers:
      - name: healer
        image: ${FULL_IMAGE}
        imagePullPolicy: Never
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
        env:
        - name: HEALER_PORT
          value: "8080"
        - name: HEALER_DRY_RUN
          value: "false"
        - name: HEALER_LOG_LEVEL
          value: "info"
        - name: HEALER_CHECK_INTERVAL
          value: "30"
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 30
          failureThreshold: 3
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 15
          failureThreshold: 3
          timeoutSeconds: 5
        securityContext:
          allowPrivilegeEscalation: false
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
YAML

# ── Step 4: Apply ─────────────────────────────────────────────────────────────
echo ""
echo "📄 Applying namespace and RBAC..."
kubectl apply --validate=false -f deployments/namespace.yaml
kubectl apply --validate=false -f deployments/rbac.yaml

echo "📄 Applying production deployment..."
kubectl apply --validate=false -f "${PROD_MANIFEST}"

echo ""
echo "⏳ Waiting for deployment (120s)..."
if ! kubectl wait --for=condition=available --timeout=120s \
    deployment/ai-predictor-healer-production -n "${NAMESPACE}" 2>/dev/null; then
  echo "⚠️  wait timed out — checking rollout status..."
  kubectl rollout status deployment/ai-predictor-healer-production -n "${NAMESPACE}"
fi

echo ""
echo "✅ Production deployment complete!"
echo "   Logs:      kubectl logs -f deployment/ai-predictor-healer-production -n ${NAMESPACE}"
echo "   Dashboard: kubectl port-forward deployment/ai-predictor-healer-production 8080:8080 -n ${NAMESPACE}"
echo "              → http://localhost:8080"
